language: node_js
dist: trusty
sudo: required

node_js:
  - "stable"

cache:
  directories:
    - node_modules # NPM packages

install:
  - npm install

script:
  - npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    target_branch: gh-pages
    on:
      branch: master

branches:
  only:
    - master
